# Generated by Django 2.1 on 2018-08-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokeh_plots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bokeh',
            name='script',
            field=models.FileField(upload_to='bokeh_test/'),
        ),
    ]
